"""HACOO 专业 Agent 注册表 — 数字芯片设计各阶段的 Agent 矩阵。

内置 Agent (stage / 职责):
  前端:  dft (可测性设计), synthesis (逻辑综合)
  后端:  apr (自动布局布线)
  签核:  sta (时序), pv (物理验证), irem (压降/电迁移), thermal (热), sipi (信号/电源完整性)
  控制:  flow (ISF 自动化平台对接: DB 管理 / CICD / Airflow flow 监视)

自由搭配与禁用:
  - hacoo.agents.json {"enabled": [...]} 控制本次实验参与的 Agent 集合
  - 网关在每次调用时强制校验: 被禁 Agent -> AGENT_DISABLED;
    Agent 调用白名单外的工具 -> AGENT_FORBIDDEN
  - `python -m hacoo agents sync` 只为启用的 Agent 生成 .opencode/agent/ 文件

知识库与决策: 见 hacoo/knowledge.py 与 hacoo/decisions.py。
"""
from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass, field
from typing import Dict, List, Optional

log = logging.getLogger("hacoo.agents")

AGENTS_CONFIG_FILE = "hacoo.agents.json"
OPENCODE_AGENT_DIR = os.path.join(".opencode", "agent")
GENERATED_MARKER = "<!-- generated by: python -m hacoo agents sync -->"


@dataclass(frozen=True)
class AgentSpec:
    name: str                 # 短名, 如 "sta"
    title: str                # 展示名
    stage: str                # frontend | backend | signoff | control
    description: str
    tools: List[str]          # 允许调用的 adapter 工具白名单
    focus: List[str] = field(default_factory=list)  # 领域关注点 (写进 prompt)

    def to_dict(self) -> Dict:
        return {"name": self.name, "title": self.title, "stage": self.stage,
                "description": self.description, "tools": self.tools, "focus": self.focus}


AGENTS: Dict[str, AgentSpec] = {a.name: a for a in [
    AgentSpec(
        name="dft", title="DFT Agent", stage="frontend",
        description="可测性设计: scan chain 插入、ATPG 覆盖率、MBIST、boundary scan。",
        tools=["icc2", "innovus", "mock_eda"],
        focus=["scan chain 规划与插入", "ATPG 覆盖率目标与 pattern 优化",
               "MBIST/BISR 策略", "测试功耗与 shift 频率权衡"]),
    AgentSpec(
        name="synthesis", title="Synthesis Agent", stage="frontend",
        description="逻辑综合: RTL -> gate netlist, 时序/面积/功耗权衡, DFT-aware 综合。",
        tools=["icc2", "innovus", "mock_eda"],
        focus=["时序驱动优化 (effort/target)", "面积与功耗 tradeoff",
               "约束完整性检查 (SDC)", "与 DFT 插入的先后次序"]),
    AgentSpec(
        name="apr", title="APR Agent", stage="backend",
        description="自动布局布线: floorplan、placement、CTS、routing; 支持 3D IC 分区与 hybrid bonding/TSV 感知。",
        tools=["icc2", "innovus", "mock_eda"],
        focus=["floorplan 与 die 分区 (3D IC)", "congestion / density 控制",
               "CTS skew 与 useful skew", "hybrid bonding / TSV 布局约束"]),
    AgentSpec(
        name="sta", title="STA Signoff Agent", stage="signoff",
        description="静态时序分析签核: 多 corner 时序、WNS/TNS、违例分类与 ECO 建议。",
        tools=["primetime", "mock_eda"],
        focus=["多 corner/multi-mode 时序收敛", "WNS/TNS 与违例路径分类",
               "时序 ECO 建议 (size/insert buffer/Vt swap)", "OCV/AOCV 裕度设置"]),
    AgentSpec(
        name="pv", title="PV Signoff Agent", stage="signoff",
        description="物理验证: DRC、LVS、ANT、ERC; 先进节点 rule deck 与 waiver 管理。",
        tools=["calibre", "mock_eda"],
        focus=["DRC 违例分类与修复优先级", "LVS 不一致定位",
               "天线效应与 ERC", "waiver 记录与追踪"]),
    AgentSpec(
        name="irem", title="IR/EM Signoff Agent", stage="signoff",
        description="压降与电迁移签核: static/dynamic IR drop、EM 寿命、PG 网络加固建议。",
        tools=["redhawk_sc", "voltus", "mock_eda"],
        focus=["static/dynamic IR drop 预算", "EM 违例与线宽/via 加固",
               "PG mesh 密度调整", "decap 插入策略"]),
    AgentSpec(
        name="thermal", title="Thermal Signoff Agent", stage="signoff",
        description="热签核: 热分布图、热点定位、3D 堆叠层间热耦合与 TTV 规划建议。",
        tools=["voltus", "redhawk_sc", "mock_eda"],
        focus=["热分布与热点阈值", "3D 堆叠层间热耦合",
               "thermal TSV / dummy 插入", "功耗图 (power map) 反馈"]),
    AgentSpec(
        name="sipi", title="SI/PI Signoff Agent", stage="signoff",
        description="信号/电源完整性: 串扰、SSN、PDN 阻抗、D2D 接口时序裕度。",
        tools=["primetime", "redhawk_sc", "mock_eda"],
        focus=["串扰 victim/aggressor 分析", "PDN 目标阻抗",
               "SSN 与同步开关噪声", "D2D/UCIe 接口裕度"]),
    AgentSpec(
        name="flow", title="ISF Flow Control Agent", stage="control",
        description="ISF 自动化平台对接: 前后端 EDA 流程串接、DB 管理、CICD 触发、Airflow flow 监视。",
        tools=["isf", "mock_eda"],
        focus=["flow 模板编排与提交", "设计 DB 版本管理",
               "CICD pipeline 触发与回归", "Airflow DAG/DagRun 状态监视"]),
]}


# ------------------------------------------------------------ 启停配置

def _config_path(path: Optional[str] = None) -> str:
    return path or os.environ.get("HACOO_AGENTS_FILE", AGENTS_CONFIG_FILE)


def load_enabled(path: Optional[str] = None) -> List[str]:
    """读取启用的 Agent 集合; 配置文件不存在时默认全部启用。

    支持 {"enabled": [...]} 或 {"disabled": [...]} 两种写法 (enabled 优先)。
    """
    cfg_path = _config_path(path)
    if not os.path.isfile(cfg_path):
        return sorted(AGENTS)
    with open(cfg_path, "r", encoding="utf-8") as fh:
        cfg = json.load(fh)
    if "enabled" in cfg:
        return [n for n in cfg["enabled"] if n in AGENTS]
    disabled = set(cfg.get("disabled", []))
    return sorted(n for n in AGENTS if n not in disabled)


def set_enabled(name: str, enabled: bool, path: Optional[str] = None) -> List[str]:
    cfg_path = _config_path(path)
    current = set(load_enabled(cfg_path))
    if name not in AGENTS:
        raise KeyError("unknown agent: '%s' (known: %s)" % (name, ", ".join(sorted(AGENTS))))
    (current.add if enabled else current.discard)(name)
    with open(cfg_path, "w", encoding="utf-8") as fh:
        json.dump({"enabled": sorted(current)}, fh, ensure_ascii=False, indent=2)
    return sorted(current)


def is_enabled(name: str, path: Optional[str] = None) -> bool:
    return name in set(load_enabled(path))


def list_agents(path: Optional[str] = None) -> List[Dict]:
    enabled = set(load_enabled(path))
    return [dict(spec.to_dict(), enabled=spec.name in enabled)
            for spec in sorted(AGENTS.values(), key=lambda s: (s.stage, s.name))]


def get(name: str) -> Optional[AgentSpec]:
    return AGENTS.get(name)


# ------------------------------------------------------------ OpenCode 同步

_AGENT_TEMPLATE = """---
description: "HACOO {title} — {description}"
mode: subagent
tools:
  hacoo*: true
  bash: false
  edit: false
  write: false
---

{marker}

You are the **{title}** of the HACOO platform (stage: {stage}), one specialist
in a multi-agent chip design team. All EDA actions go through `hacoo_*` MCP
tools only.

# Domain focus
{focus_bullets}

# Identity & traceability (MANDATORY)
- Your agent name is `{name}`. Pass `agent="{name}"` in every `hacoo_call`,
  and `run_id` when working inside a flow run. This is how the platform
  attributes decisions to you (accountability).
- You may ONLY use these backend tools: {tools}. Calls outside your allowlist
  are rejected with `AGENT_FORBIDDEN`.

# Knowledge loop (self-improvement, MANDATORY)
1. BEFORE making a non-trivial decision, query your knowledge base:
   `hacoo_knowledge_query(agent="{name}", keyword=<topic>)` — reuse past lessons.
2. For every key decision, record it BEFORE acting:
   `hacoo_decision_record(agent="{name}", run_id=..., stage="{stage}",
   action=..., rationale=..., params=...)` → keep the returned decision_id.
3. AFTER the action, close the loop:
   `hacoo_decision_outcome(decision_id=..., status="ok"|"failed", metrics=..., note=...)`.
4. When you hit a NEW problem and solve it, persist the lesson:
   `hacoo_knowledge_add(agent="{name}", symptom=..., root_cause=...,
   resolution=..., tags=[...])` so you never solve the same problem twice.

# Rules
- Never invent numbers the backend did not return.
- On `AGENT_DISABLED` / `AGENT_FORBIDDEN`, stop and report to the orchestrator —
  do not work around the policy.
"""


def render_agent_md(spec: AgentSpec) -> str:
    return _AGENT_TEMPLATE.format(
        name=spec.name, title=spec.title, stage=spec.stage,
        description=spec.description,
        tools=", ".join(spec.tools),
        focus_bullets="\n".join("- " + f for f in spec.focus),
        marker=GENERATED_MARKER)


def sync_opencode(agent_dir: str = OPENCODE_AGENT_DIR,
                  path: Optional[str] = None) -> Dict[str, List[str]]:
    """为启用的 Agent 生成 .opencode/agent/hacoo-<name>.md; 清理被禁 Agent 的旧文件。"""
    os.makedirs(agent_dir, exist_ok=True)
    enabled = set(load_enabled(path))
    written, removed = [], []
    for name, spec in AGENTS.items():
        target = os.path.join(agent_dir, "hacoo-%s.md" % name)
        if name in enabled:
            with open(target, "w", encoding="utf-8") as fh:
                fh.write(render_agent_md(spec))
            written.append(target)
        elif os.path.isfile(target):
            with open(target, "r", encoding="utf-8") as fh:
                if GENERATED_MARKER in fh.read():
                    try:
                        os.remove(target)
                        removed.append(target)
                    except OSError as exc:
                        log.warning("cannot remove %s: %s (file in use?)", target, exc)
    return {"written": sorted(written), "removed": sorted(removed)}
